name = "playground"
type = "javascript"
account_id = "fecf0c3774273cf63ed8664432ff363f"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "npm run build"
upload.format = "service-worker"