// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Contact': typeof import('../components/contact/contact.vue')['default'],
    'DeskResearch': typeof import('../components/desk-research/desk-research.vue')['default'],
    'DesignConcepts': typeof import('../components/design-concepts/design-concepts.vue')['default'],
    'DesignConceptsUsabilityStudy': typeof import('../components/design-concepts/usability-study.vue')['default'],
    'ResumeImage': typeof import('../components/resume/resume-image.vue')['default'],
    'ResumeNew': typeof import('../components/resume/resume-new.vue')['default'],
    'Resume': typeof import('../components/resume/resume.vue')['default'],
    'Hero': typeof import('../components/hero/hero.vue')['default'],
    'HeroPhones': typeof import('../components/hero/phones.vue')['default'],
    'HeroSteps': typeof import('../components/hero/steps.vue')['default'],
    'ScreensScreenNumberTitle': typeof import('../components/screens/screen-number-title.vue')['default'],
    'Screens': typeof import('../components/screens/screens.vue')['default'],
    'SharedFigmaLink': typeof import('../components/shared/figma-link.vue')['default'],
    'SharedImage': typeof import('../components/shared/image.vue')['default'],
    'SharedNumberedTitle': typeof import('../components/shared/numbered-title.vue')['default'],
    'SharedTextWithFigure': typeof import('../components/shared/text-with-figure.vue')['default'],
    'SharedTitle': typeof import('../components/shared/title.vue')['default'],
    'Shenkar': typeof import('../components/shenkar/shenkar.vue')['default'],
    'TestValidationBasicFlow': typeof import('../components/test-validation/basic-flow.vue')['default'],
    'TestValidationLowFidelity': typeof import('../components/test-validation/low-fidelity.vue')['default'],
    'TestValidationTextValidation': typeof import('../components/test-validation/text-validation.vue')['default'],
    'TextAndFiguresPersona': typeof import('../components/text-and-figures/persona.vue')['default'],
    'TextAndFiguresBig': typeof import('../components/text-and-figures/text-and-figures-big.vue')['default'],
    'TextAndFiguresSmall': typeof import('../components/text-and-figures/text-and-figures-small.vue')['default'],
    'ResumeInfoEducation': typeof import('../components/resume/resume-info/resume-info-education.vue')['default'],
    'ResumeInfoExperience': typeof import('../components/resume/resume-info/resume-info-experience.vue')['default'],
    'ResumeInfo': typeof import('../components/resume/resume-info/resume-info.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
